---
- project:
    name: SovereignCloudStack/security-infra-scan-pipeline
    default-branch: main
    merge-mode: "squash-merge"
    periodic-daily:
      jobs:
        - scs-daily-security-scan
    post:
      jobs:
        - noop
    check:
      jobs:
        - noop
- job:
    name: scs-daily-security-scan
    parent: base
    secrets:
     - name: pipeline_conf
       secret: SECRET_SECURITY_INFRA_SCAN_PIPELINE
    pre-run: playbooks/pre.yaml
    run: playbooks/daily-scan.yaml
