---
- project:
    name: SovereignCloudStack/security-infra-scan-pipeline
    default-branch: main
    merge-mode: "squash-merge"
    periodic-daily:
      jobs:
        - scs-daily-security-scan
    periodic-weekly:
      jobs:
        - scs-weekly-security-scan
    post:
      jobs:
        - noop
    check:
      jobs:
        - noop

- job:
    name: scs-daily-security-scan
    parent: base
    timeout: 7200 #2h
    secrets:
     - name: pipeline_conf
       secret: SECRET_SECURITY_INFRA_SCAN_PIPELINE
    pre-run: playbooks/pre.yaml
    run: playbooks/daily-scan.yaml
    vars:
      # TODO: engagement_id is not a secret, define id here directly
      # Since in Zuul it is not possible to define vars from secrets on the
      # job level pass a key name down to the job
      engagement: "daily_scan_engagement_id"

- job:
    name: scs-weekly-security-scan
    parent: base
    timeout: 21600 #6h
    secrets:
     - name: pipeline_conf
       secret: SECRET_SECURITY_INFRA_SCAN_PIPELINE
    pre-run: playbooks/pre.yaml
    run: playbooks/weekly-scan.yaml
    vars:
      # TODO: engagement_id is not a secret, define id here directly
      # Since in Zuul it is not possible to define vars from secrets on the
      # job level pass a key name down to the job
      engagement: "weekly_scan_engagement_id"
