---
# individual scans are sharing data with each other using mounted volume, so the order matters
- name: Invoke Naabu scan
  ansible.builtin.import_playbook: naabu.yaml

- name: Invoke httpx scan
  ansible.builtin.import_playbook: httpx.yaml

- name: Invoke nuclei scan
  ansible.builtin.import_playbook: nuclei.yaml

- name: Invoke OWASP ZAP scan
  ansible.builtin.import_playbook: owasp-zap.yaml
