---
- name: Perform scan with Greenbone
  hosts: all
  tasks:

    - name: Start Greenbone containers
      become: true
      ansible.builtin.shell: |
        docker-compose -f {{ scan_work_dir }}/greenbone-compose.yaml -p greenbone-community-edition up -d

    # https://greenbone.github.io/docs/latest/22.4/container/workflows.html#exposing-gvmd-unix-socket-for-gmp-access
    - name: Wait until gvmd socket is present before continuing (/tmp/gvm/gvmd/gvmd.sock)
      ansible.builtin.wait_for:
        path: /tmp/gvm/gvmd/gvmd.sock
        state: present

    - name: Wait for GVM to start and feeds to update
      ansible.builtin.shell: |
        gvm-cli --gmp-username "admin" --gmp-password "admin" socket --socketpath /tmp/gvm/gvmd/gvmd.sock --xml "<get_feeds/>"
      register: feed_status
      until: "'<currently_syncing>' not in feed_status.stdout"
      retries: 60
      delay: 60
      changed_when: false

    - name: Execute the GVM scan script
      ansible.builtin.shell: |
        python3 {{ scan_work_dir }}/gvm_scan.py --reports-dir {{ scan_results_dir }}/gvm_reports {{ ['--target'] | product(scan_targets) | map('join', ' ') | join(' ') }}
      register: scan_result

    - name: Find Greenbone reports
      ansible.builtin.find:
        paths: "{{ scan_results_dir }}/gvm_reports"
        patterns: "*.xml"
      register: "gvm_reports"

    - name: Read in Greenbone reports content
      ansible.builtin.slurp:
        src: "{{ item.path }}"
      loop: "{{ gvm_reports.files }}"
      register: "gvm_reports_content"

    - name: Send Greenbone results to Defect Dojo
      no_log: true
      ansible.builtin.uri:
        url: "{{ pipeline_conf.dojo_url }}"
        headers:
          Authorization: "{{ ('Token ' + pipeline_conf.dojo_api_key) if pipeline_conf.dojo_api_key is defined else pipeline_conf.dojo_auth }}"
        method: "POST"
        body_format: "form-multipart"
        body:
          engagement: "{{ pipeline_conf[engagement] }}"
          scan_type: "OpenVAS Parser"
          verified: "true"
          active: "true"
          skip_duplicates: "false"
          close_old_findings: "true"
          file: "{{ zj_item['content'] | b64decode }}"
      loop: "{{ gvm_reports_content.results }}"
      loop_control:
        loop_var: zj_item
      when:
        - "engagement is defined and engagement"
        - "pipeline_conf is defined"
