---
  #Identify web services running across thee results forwarded by naabu
  #Output: urls in the form of http[s]://IP:Port
- name: Perform Scan with httpx
  hosts: all
  tasks:
    # Invoke httpx container waiting for the container to complete
    - name: Run httpx scan
      community.docker.docker_container:
        name: httpx_scan
        image: "projectdiscovery/httpx"
        command: "-l /tmp/scan_results/naabu-results.txt -o /tmp/scan_results/httpx-results.txt"
        volumes:
          - "{{ scan_work_dir }}:/tmp"
        state: "started"
        detach: false
      register: httpx_container_result
