---
- name: Perform scan with naabu
  hosts: all
  tasks:

    # Invoke naabu container waiting for the container to complete
    - name: Run naabu scan
      community.docker.docker_container:
        name: naabu_scan
        image: "projectdiscovery/naabu"
        command: "-host {{ scan_targets | default([ansible_ssh_host]) | list | join(',') }} -o /tmp/scan_results/naabu-results.txt"
        state: "started"
        detach: false
        auto_remove: true
        volumes:
          - "{{ scan_work_dir }}:/tmp"
      register: naabu_container_result
