---
- name: Perform scan with Nuclei
  hosts: all
  tasks:

    # Invoke nuclei container waiting for the container to complete
    - name: Run nuclei scan
      community.docker.docker_container:
        name: nuclei_scan
        image: "projectdiscovery/nuclei"
        command: "-list /tmp/scan_results/httpx-results.txt -j -o /tmp/scan_results/nuclei-results.json"
        volumes:
          - "{{ scan_work_dir }}:/tmp"
        state: "started"
        detach: false
        auto_remove: true
      register: nuclei_container_result

    - name: Find Nuclei report
      ansible.builtin.find:
        paths: "{{ scan_results_dir }}"
        patterns: "nuclei-results.json"
      register: "nuclei_reports"

    - name: Read in Nuclei report content
      ansible.builtin.slurp:
        src: "{{ item.path }}"
      loop: "{{ nuclei_reports.files }}"
      register: "nuclei_reports_content"

    - name: Send Nuclei results to Defect Dojo
      no_log: true
      ansible.builtin.uri:
        url: "{{ pipeline_conf.dojo_url }}"
        headers:
          Authorization: "{{ ('Token ' + pipeline_conf.dojo_api_key) if pipeline_conf.dojo_api_key is defined else pipeline_conf.dojo_auth }}"
        method: "POST"
        body_format: "form-multipart"
        body:
          engagement: "{{ pipeline_conf[engagement] }}"
          scan_type: "Nuclei Scan"
          verified: "true"
          active: "true"
          skip_duplicates: "false"
          close_old_findings: "true"
          file: "{{ zj_item['content'] | b64decode }}"
      loop: "{{ nuclei_reports_content.results }}"
      loop_control:
        loop_var: zj_item
      when:
        - "engagement is defined and engagement"
        - "pipeline_conf is defined"
