---
- name: Install pipeline pre-requisites
  hosts: all
  roles:
    - role: ensure-pip
    - role: ensure-docker
      vars:
        docker_compose_install: true
  tasks:
    - name: Install docker python library
      ansible.builtin.pip:
        name:
        - "docker"

    - name: Install python-gvm library (Greenbone)
      ansible.builtin.pip:
        name:
        - "python-gvm"
        state: present

    - name: Install gvm-tools (Greenbone)
      become: true
      ansible.builtin.pip:
        name: 
        - "gvm-tools"
        state: present

    - name: Check if docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: true

    - name: Copy Files on the node
      ansible.builtin.copy:
        src: "../files/"
        dest: "{{ scan_work_dir }}"
        mode: 0500
      no_log: false

    - name: Ensure scan output directory exists
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ scan_results_dir }}/zap_reports"
        - "{{ scan_results_dir }}/gvm_reports"

    - name: Check if greenbone folder for socket bind mount exists
      ansible.builtin.file:
        path: "/tmp/gvm/gvmd"
        state: directory
        mode: '1777'
        recurse: true
